using System;
using Game.Core.FactoryPool;
using UnityEngine;

namespace Game.Game.Level.Views
{
    /// <summary>
    /// Poolable ObstacleView
    /// Generated by ObstaclesGenerator
    /// </summary>
    public class Obstacle : MonoBehaviour,IPooledObject
    {
        public Renderer Renderer;
        [HideInInspector] public bool isVisible = true;


        private void OnBecameInvisible()
        {
            isVisible = false;
        }

        private void OnBecameVisible()
        {
            isVisible = true;
        }
    }
}